# Generated by Django 3.2.8 on 2021-10-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipeChoiceTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('wait', 'Chưa mở'), ('open', 'Đang mở'), ('close', 'Đã đóng')], default='wait', max_length=10),
        ),
    ]
