# Generated by Django 3.2.8 on 2021-10-21 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MultipeChoiceTest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.AddField(
            model_name='question',
            name='exam_c',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MultipeChoiceTest.exam'),
            preserve_default=False,
        ),
    ]
