# Generated by Django 3.2.8 on 2021-11-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipeChoiceTest', '0002_alter_studentexam_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexam',
            name='joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
