# Generated by Django 3.2.8 on 2021-11-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultipeChoiceTest', '0002_alter_exam_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='schedule_close',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='schedule_open',
        ),
    ]
