# Generated by Django 3.2.8 on 2021-11-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultipeChoiceTest', '0004_alter_exam_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='questions',
        ),
    ]
