# Generated by Django 3.2.8 on 2021-11-02 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultipeChoiceTest', '0005_remove_exam_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
    ]
