# Generated by Django 3.2.8 on 2021-10-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipeChoiceTest', '0005_auto_20211021_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
