# Generated by Django 3.2.8 on 2021-11-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultipeChoiceTest', '0006_alter_exam_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(help_text='Tính bằng phút', verbose_name='Thời gian làm bài thi'),
        ),
    ]
